/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ReputexWidget {
        "apiAccessKey": string;
        "apiSecretKey": string;
        "mode": boolean;
        "userAddress": string;
        "visibility": boolean;
    }
    interface ScoreLoaded {
        "isDid": boolean;
        "lastUpdated": string;
        "mode": boolean;
        "reputeXScore": number;
        "userAddress": string;
    }
}
declare global {
    interface HTMLReputexWidgetElement extends Components.ReputexWidget, HTMLStencilElement {
    }
    var HTMLReputexWidgetElement: {
        prototype: HTMLReputexWidgetElement;
        new (): HTMLReputexWidgetElement;
    };
    interface HTMLScoreLoadedElement extends Components.ScoreLoaded, HTMLStencilElement {
    }
    var HTMLScoreLoadedElement: {
        prototype: HTMLScoreLoadedElement;
        new (): HTMLScoreLoadedElement;
    };
    interface HTMLElementTagNameMap {
        "reputex-widget": HTMLReputexWidgetElement;
        "score-loaded": HTMLScoreLoadedElement;
    }
}
declare namespace LocalJSX {
    interface ReputexWidget {
        "apiAccessKey"?: string;
        "apiSecretKey"?: string;
        "mode"?: boolean;
        "userAddress"?: string;
        "visibility"?: boolean;
    }
    interface ScoreLoaded {
        "isDid"?: boolean;
        "lastUpdated"?: string;
        "mode"?: boolean;
        "reputeXScore"?: number;
        "userAddress"?: string;
    }
    interface IntrinsicElements {
        "reputex-widget": ReputexWidget;
        "score-loaded": ScoreLoaded;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "reputex-widget": LocalJSX.ReputexWidget & JSXBase.HTMLAttributes<HTMLReputexWidgetElement>;
            "score-loaded": LocalJSX.ScoreLoaded & JSXBase.HTMLAttributes<HTMLScoreLoadedElement>;
        }
    }
}
